### ISSUE TITLE
Federation over Tor

### ISSUE THREAD

**Issue by ch0ccyra1n** [sublinks/sublinks-federation#44]
Is it yet possible to federate sublinks over Tor (or for that matter, any HTTP or SOCKS proxy)? I'd like to set up a hidden service sublinks instance at some point.

**Comment by lazyguru** [comment]
I don't see how this would be a feature we would should need to _specifically_ to support? Tor should be configured at the OS level and proxy all outbound traffic. As long as we respect any OS level proxy configuration then it should "just work"
